### ISSUE TITLE
Services Single : Incorrect slug used.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Matt-Tucker-Design-Studio#26]
![26](https://cloud.githubusercontent.com/assets/18256652/16104482/621319e2-33b4-11e6-8eb9-16742b65138f.png)

![26a](https://cloud.githubusercontent.com/assets/18256652/16106145/82958d70-33c4-11e6-912e-cbfad82fa171.png)

**Comment by jewelcantuba** [comment]
Cannot be fixed because the slug being referred is the custom post type name.
