### ISSUE TITLE
Homepage - Content : A character of linked text dropped, please adjust it can still fit on the space to become one line.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Matt-Tucker-Design-Studio#39]
![39](https://cloud.githubusercontent.com/assets/18256652/16108246/9fe402f2-33d4-11e6-9088-2fc69ca78d34.png)

**Comment by jewelcantuba** [comment]
Not a bug. Content posting error. The link and content specifically the word 'Perth' was concatenated/link that's why it reached to the next line. There is no space between the link and the word 'Perth'.

**Comment by iteano** [comment]
Change to fixed.
